<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-9ODPH64" name="com.salesforce.testcases.TC_004_Learning_On_Trailhead" tests="2" failures="0" timestamp="2022-09-23T16:10:38 IST" time="10.693" errors="1">
  <testcase name="runLogin" time="5.227" classname="com.salesforce.testcases.TC_004_Learning_On_Trailhead">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.framework.utils.Reporter.reportStep(Reporter.java:91)
at com.framework.utils.Reporter.reportStep(Reporter.java:108)
at com.salesforce.pages.LoginPage.enterUsername(LoginPage.java:14)
at com.salesforce.testcases.TC_004_Learning_On_Trailhead.runLogin(TC_004_Learning_On_Trailhead.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- runLogin -->
  <system-out/>
  <testcase name="runScenario" time="5.466" classname="com.salesforce.testcases.TC_004_Learning_On_Trailhead">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- com.salesforce.testcases.TC_004_Learning_On_Trailhead -->
